# Project: Jogo da forca
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Jogo\ da\ forca.o"
LINKOBJ  = "Jogo da forca.o"
LIBS     = -L"C:/Meus Programas/Dev-Cpp/MinGW64/lib" -L"C:/Meus Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Meus Programas/Dev-Cpp/MinGW64/include" -I"C:/Meus Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Meus Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Meus Programas/Dev-Cpp/MinGW64/include" -I"C:/Meus Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Meus Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Meus Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Jogo da forca.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"Jogo\ da\ forca.o": Jogo\ da\ forca.cpp
	$(CPP) -c "Jogo da forca.cpp" -o "Jogo da forca.o" $(CXXFLAGS)
